myshop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

myshop/cupons/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^apply/$', views.CuponApply, name='apply')
]

myshop/myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^auth/', include('userauth.urls', namespace='auth')),
    url(r'^wishlist/', include('wishlist.urls', namespace='wishlist')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('shop.urls', namespace='shop'))
]

# настройки для работи з медіа файлами
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.AdminOrderDetail, name='AdminOrderDetail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.AdminOrderPDF, name='AdminOrderPDF')
]

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomePage, name='HomePage'),
    url(r'^categories/$', views.ProductList, name='ProductList'),
    url(r'^brands/$', views.BrandList, name='BrandList'),
    url(r'^brand/(?P<brand_slug>[-\w]+)/$', views.ProductList, name='ProductListByBrand'),
    url(r'^poster/(?P<poster_slug>[-\w]+)/$', views.ProductList, name='ProductListByPoster'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^catalog/(?P<catalog_slug>[-\w]+)/$', views.CatalogList, name='ProductListByCatalog'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^poster/(?P<poster_id>\d+)/(?P<poster_slug>[-\w]+)/$', views.PosterDetail, name='PosterDetail'),
    url(r'^contacts/$', views.Contacts, name='Contacts'),
    url(r'^guarantee/$', views.Guarantee, name='Guarantee'),
    url(r'^about/$', views.About, name='About'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
# **************************************************************
# Форма для того, щоб користувач міг вибирати кількість товару *
# **************************************************************
from django import forms

# генератор вибору кількості продукта [(1, '1'), (2, '2'), (3, '3'),..., (19, '19'), (20, '20')]
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    # поле призначенне для вибору товару select :
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Кількість",
                                      widget=forms.Select(attrs={'class': 'selectpicker', 'data-width': '55px', })
                                      )
    # поле превірки чи товар був раніше доданий в корзину:
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cupons.forms import CuponApllyForm

# декоратор дозволяє обробляти тільки POST запити
@require_POST
def CartAdd(request, product_id):
    # в'юха дадавання товару в корзину
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:CartDetail')


# в'юха видалення товару з корзини
def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


# в'юха відображення товару з корзини отримує єкземпляр корзини користувача
# і передає його в якості параметра в шаблон. Створюєм екземпляр класа
# CartAddProductForm для кожного товара нашої корзини, це дасть змогу змінювати
# кількість товарів на сторінці корзини товарів. Виставляєм в  поля update
# значення True. Таким чином старе значення буде перезаписано новим.
# cupon_apply_form відображає форму купона в корзині
def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    cupon_apply_form = CuponApllyForm()
    return render(request, 'cart/detail.html',
                 {'cart': cart, 'cupon_apply_form': cupon_apply_form})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Ваш кошик товарів
{% endblock %}

{% block content %}
<!-- ================================================= BREADCRUMB ================================================== -->
<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url 'shop:HomePage' %}">Головна</a></li>
				<li class='active'>Ваш кошик товарів</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->
<!-- ============================================= BREADCRUMB : END ================================================ -->
<!-- ================================================ CARD DETAIL ================================================== -->
<div class="body-content outer-top-xs">
	<div class="container">
		<div class="row ">
			<div class="shopping-cart">
<div class="shopping-cart-table ">
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th class="cart-romove item">Видалити</th>
					<th class="cart-description item">Зображення</th>
					<th class="cart-product-name item">Назва продукту</th>
					<th class="cart-qty item">Кількість</th>
					<th class="cart-sub-total item">Ціна за 1 товару</th>
					<th class="cart-total last-item">Сумарна ціна</th>
				</tr>
			</thead><!-- /thead -->
			<tfoot>
				<tr>
					<td colspan="7">
						<div class="shopping-cart-btn">
							<span class="">
								<a href="{% url "shop:ProductList"%}" class="btn btn-upper btn-primary outer-left-xs">Продовжити покупки</a>
{#								<a href="#" class="btn btn-upper btn-primary pull-right outer-right-xs">Update shopping cart</a>#}
							</span>
						</div><!-- /.shopping-cart-btn -->
					</td>
				</tr>
			</tfoot>
			<tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td class="romove-item"><a href="{% url "cart:CartRemove" product.id %}" title="cancel" class="icon"><i class="fa fa-trash-o"></i></a></td>
                        <td class="cart-image">
                            <a class="entry-thumbnail" href="{{ product.get_absolute_url }}">
                                <img src="{{ product.image.url }}" alt="" />
                            </a>
                        </td>
                        <td class="cart-product-name-info">
                            <h4 class='cart-product-description'><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- rating stars -->
                                    {% if product.avg_review == None %}
                                            <span class="stars-avg stars0"></span>
                                        {% else %}
                                        <span class="stars-avg stars{{product.avg_review|floatformat:"0"}}"></span>
                                    {%endif%}
                                    <!-- rating stars : end -->
                                </div>
                                <div class="col-sm-8">
                                </div>
                            </div><!-- /.row -->
                            <div class="cart-product-info">
                                <span class="product-color">{{ product. }}<span>Blue</span></span>
                            </div>
                        </td>
                        <td>
                          <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            {% csrf_token %}
                            <input type="submit" value="Оновити">
                          </form>
                        </td>

                        <td class="cart-product-sub-total"><span class="cart-sub-total-price">{{ item.price }} грн.</span></td>
                        <td class="cart-product-grand-total"><span class="cart-grand-total-price">{{ item.total_price }} грн.</span></td>
                    </tr>
                    {% endwith %}
                {% endfor %}
			</tbody><!-- /tbody -->
		</table><!-- /table -->
	</div>
</div><!-- /.shopping-cart-table -->

<!---------------------------------------------COUPONS APPLY FORM------------------------------------------------------>
{#  <p>Застосувати купон</p>#}
{#  <form action="{% url "cupon:apply" %}" method="post" class="add">#}
{#    {% csrf_token %}#}
{#    {{ cupon_apply_form }}#}
{#    <input type="submit" value="Оновити">#}
{#  </form>#}
<!---------------------------------------------COUPONS APPLY FORM : END------------------------------------------------>

<div class="col-md-6 col-sm-12 estimate-ship-tax">
	<table class="table">
		<thead>
			<tr>
				<th>
					<span class="estimate-title">Код купона</span>
					<p>Будь ласка, введіть свій купон, а потім натисніть "Застосувати"..</p>
				</th>
			</tr>
		</thead>
		<tbody>
				<tr>
					<td>
                        <form action="{% url "cupon:apply" %}" method="post" class="add">
                            <div class="form-group">
                                {% csrf_token %}
                                {{ cupon_apply_form.code }}
                            </div>
                            <div class="clearfix pull-right">
                                <input type="submit" class="btn-upper btn btn-primary" value="Застосувати">
                            </div>
                        </form>
					</td>
				</tr>
		</tbody><!-- /tbody -->
	</table><!-- /table -->
</div><!-- /.estimate-ship-tax -->



<!---------------------------------------------SUMARY  : END------------------------------------------------>
<div class="col-md-6 col-sm-12 cart-shopping-total">
	<table class="table">
		<thead>
			<tr>
				<th>
                    {% if cart.cupon %}
                        <div class="cart-sub-total">
						    Вартість без знижки<span class="inner-left-md">{{ cart.get_total_price }}</span>
					    </div>
                        <div class="cart-sub-total">
                              "{{ cart.cupon.code }}" купон на ({{ cart.cupon.discount }} % нижще) : - {{ cart.get_discount|floatformat:"2" }} грн.
                        </div>
                    {% endif %}

					<div class="cart-grand-total">
						Загальна сума :<span class="inner-left-md">{{ cart.get_total_price_after_discount|floatformat:"2" }} грн.</span>
					</div>
				</th>
			</tr>
		</thead><!-- /thead -->
		<tbody>
				<tr>
					<td>
						<div class="cart-checkout-btn pull-right">
                            <a href="{% url "orders:OrderCreate" %}" class="btn btn-primary checkout-btn">Оформити замовлення</a>
{#							<span class="">Checkout with multiples address!</span>#}
						</div>
					</td>
				</tr>
		</tbody><!-- /tbody -->
	</table><!-- /table -->
</div><!-- /.cart-shopping-total -->
            </div><!-- /.shopping-cart -->
		</div> <!-- /.row -->
    </div>  <!-- /.container -->
</div>  <!-- /.body-content outer-top-xs -->

<!-- =============================================== CARD DETAIL : END ================================================== -->

{% endblock %}