myshop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

myshop/myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^auth/', include('userauth.urls', namespace='auth')),
    url(r'^wishlist/', include('wishlist.urls', namespace='wishlist')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('shop.urls', namespace='shop'))
]

# настройки для работи з медіа файлами
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomePage, name='HomePage'),
    url(r'^categories/$', views.ProductList, name='ProductList'),
    url(r'^brands/$', views.BrandList, name='BrandList'),
    url(r'^brand/(?P<brand_slug>[-\w]+)/$', views.ProductList, name='ProductListByBrand'),
    url(r'^poster/(?P<poster_slug>[-\w]+)/$', views.ProductList, name='ProductListByPoster'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^catalog/(?P<catalog_slug>[-\w]+)/$', views.CatalogList, name='ProductListByCatalog'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^poster/(?P<poster_id>\d+)/(?P<poster_slug>[-\w]+)/$', views.PosterDetail, name='PosterDetail'),
    url(r'^contacts/$', views.Contacts, name='Contacts'),
    url(r'^guarantee/$', views.Guarantee, name='Guarantee'),
    url(r'^about/$', views.About, name='About'),
]

myshop/userauth/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.RegisterUser, name='RegisterUser'),
    url(r'^login/$', views.LoginUser, name='LoginUser'),
    url(r'^logout/$', views.LogoutUser, name='LogoutUser'),
    url(r'^profile/$', views.ProfileUser, name='ProfileUser'),
    url(r'^profile/edit/$', views.ProfileEdit, name='ProfileEdit'),
]

myshop/wishlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.WishListView, name='WishListView'),
    url(r'^add/(?P<product_id>\d+)/$', views.WishListAdd, name='WishListAdd'),
    url(r'^delete/(?P<product_id>\d+)/$', views.WishListDelete, name='WishListDelete'),

]

myshop/shop/forms.py
# **************************************************************
# Форма для того, щоб користувач міг вибирати кількість товару *
# **************************************************************

from django import forms
from .models import Comment


class CommentAddForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['product', 'created', 'author', 'verificated']
        widgets = {
            'text_comment': forms.Textarea(attrs={'class': 'form-control txt txt-review', 'rows': '5'}),
            # 'rating': forms.CheckboxSelectMultiple()
            }

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response,HttpResponseRedirect,reverse
from .models import Catalog, Category, Product, Comment, Brand, Poster
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentAddForm
from django.db.models import Avg

# Сторінка з товарами
def HomePage(request, category_slug=None):
    category = None
    catalog = None
    # new_products=None
    catalogs = Catalog.objects.all()
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    products = Product.objects.filter(available=True)
    new_products = Product.objects.filter(available=True, tag_status='new').order_by('-created')[:6]
    new_products_el = Product.objects.filter(available=True, tag_status='new', category__catalog__name='Електротовари').order_by('-created')[:6]
    new_products_auto = Product.objects.filter(available=True, tag_status='new', category__catalog__name='Автотовари').order_by('-created')[:6]
    new_products_sant = Product.objects.filter(available=True, tag_status='new', category__catalog__name='Сантехніка').order_by('-created')[:6]
    best_products = Product.objects.filter(available=True).order_by('?')[:6]
    top_sales_products = Product.objects.filter(available=True, tag_status='hot').order_by('-created')[:6]
    hot_deals_products = Product.objects.filter(available=True, tag_status='hot').order_by('?')[:3]
    special_deals_products = Product.objects.filter(available=True).order_by('?')[:9]

    posters = Poster.objects.filter(active=True).order_by('-created')[:5]
    posters_one = Poster.objects.filter(active=True).order_by('created')[:1]

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/home.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'catalog': catalog,
        'catalogs': catalogs,
        'posters': posters,
        'posters_one': posters_one,
        'cart_product_form': cart_product_form,
        'new_products': new_products,
        'new_products_el': new_products_el,
        'new_products_auto': new_products_auto,
        'new_products_sant': new_products_sant,
        'best_products': best_products,
        'top_sales_products': top_sales_products,
        'hot_deals_products': hot_deals_products,
        'special_deals_products': special_deals_products,

    })

# Сторінка відображення каталогу з категоріями
def CatalogList(request, catalog_slug=None):
    catalog = None
    catalogs = Catalog.objects.all()
    categories = Category.objects.all()
    posters = Poster.objects.filter(active=True).order_by('-created')[:5]
    if catalog_slug:
        catalog = get_object_or_404(Catalog, slug=catalog_slug)
        categories = categories.filter(catalog=catalog)
    return render(request, 'shop/product/catalog_list.html', {
        'catalog': catalog,
        'catalogs': catalogs,
        'categories': categories,
        'posters': posters,
    })


# Сторінка з товарами
def ProductList(request, category_slug=None, brand_slug=None, poster_slug=None):
    category = None
    catalog = None
    catalogs = Catalog.objects.all()
    categories = Category.objects.all()
    products_list = Product.objects.filter(available=True).annotate(avg_review=Avg('comments__rating'))
    cart_product_form = CartAddProductForm()
    posters = Poster.objects.filter(active=True).order_by('-created')[:5]

    page = request.GET.get('page', 1)
    paginator = Paginator(products_list, 9)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)
        paginator = Paginator(products_list, 9)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        products_list = products_list.filter(brand=brand)
        paginator = Paginator(products_list, 9)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    if poster_slug:
        poster = get_object_or_404(Poster, slug=poster_slug)
        products_list = products_list.filter(poster=poster)
        paginator = Paginator(products_list, 9)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'catalog': catalog,
        'catalogs': catalogs,
        'cart_product_form': cart_product_form,
        'posters': posters,
    })


# Сторінка товару
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    if request.method == 'POST':
        comment_form = CommentAddForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.product = product
            comment.save()
            return HttpResponseRedirect(reverse('shop:ProductDetail', args=[id, slug]))
    else:
        comment_form = CommentAddForm()

    comments_list = Comment.objects.filter(product=product, verificated=True)
    # Сума всіх оцінок і коментаріїв
    review_sum = Product.objects.filter(slug=slug).annotate(avg_review=Avg('comments__rating'))
    review_count = Comment.objects.filter(product__slug=slug, verificated=True).count()
    hot_deals_products = Product.objects.filter(available=True, tag_status='hot').order_by('?')[:3]
    best_products = Product.objects.filter(available=True).order_by('?')[:6]
    posters_one = Poster.objects.filter(active=True).order_by('created')[:1]
    brands = Brand.objects.all()[:12]

    return render(request, 'shop/product/detail.html', {
        'product': product,
        'cart_product_form': cart_product_form,
        'comment_form': comment_form,
        'comments_list': comments_list,
        'review_sum': review_sum,
        'review_count': review_count,
        'hot_deals_products': hot_deals_products,
        'best_products': best_products,
        'posters_one': posters_one,
        'brands': brands,
    })


def BrandList(request):
    brands = Brand.objects.all()
    brands_popular = Brand.objects.all().order_by('?')[:12]
    # filter(products__comments__rating=1)
    return render(request, 'shop/brand/brand_list.html', {
        'brands': brands,
        'brands_popular': brands_popular,
    })

def PosterDetail(request,poster_id, poster_slug):
    poster = get_object_or_404(Poster, slug=poster_slug, id=poster_id)
    brands_popular = Brand.objects.all().order_by('?')[:12]
    products_poster = Product.objects.filter(available=True, poster__slug=poster_slug).order_by('-created')[:6]
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/poster/poster_detail.html', {
        'poster': poster,
        'brands_popular': brands_popular,
        'products_poster': products_poster,
        'cart_product_form': cart_product_form,
    })

def Contacts(request):
    return render(request, 'shop/other/contacts.html')

def Guarantee(request):
    return render(request, 'shop/other/guarantee.html')

def About(request):
    return render(request, 'shop/other/about.html')


# ----------------------------------------------------------------------------------------------------------------------
# # Сторінка з товарами
# def ProductList(request, category_slug=None):
#     category = None
#     catalog = None
#     categories = Category.objects.all()
#     catalogs = Catalog.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         # category = get_object_or_404(Category, slug=category_slug)
#         catalog = get_object_or_404(Catalog, slug=category_slug)
#         categories = categories.filter(catalog=catalog)
#         products = products.filter(category=category)
#     return render(request, 'shop/product/list.html', {
#         'catalog': catalog,
#         'catalogs': catalogs,
#         # 'category': category,
#         'categories': categories,
#         'products': products
#     })


# # Сторінка з товарами
# def ProductList(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = products.filter(category=category)
#     return render(request, 'shop/product/list.html', {
#         'category': category,
#         'categories': categories,
#         'products': products
#     })

myshop/shop/templates/shop/poster/poster_detail.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
  {% if poster.name %}{{ poster.name }}{% endif %}
{% endblock %}

{% block content %}
<!-- =============================================== BRADCRUMB ===================================================== -->
<div class="breadcrumb">
	<div class="container">
		<div class="breadcrumb-inner">
			<ul class="list-inline list-unstyled">
				<li><a href="{% url "shop:ProductList" %}">Головна</a></li>
{#				<li><a href="{{ product.category.get_absolute_url }}"><span>{% if product.name %} {{ product.category }}{% endif %}</span></a></li>#}
				<li class='active'>{% if poster.name %}{{ poster.name }}{% endif %}</li>
			</ul>
		</div><!-- /.breadcrumb-inner -->
	</div><!-- /.container -->
</div><!-- /.breadcrumb -->
<!-- =========================================== BRADCRUMB : END =================================================== -->
<!-- =============================================== CONTENT ======================================================= -->
<div class="body-content outer-top-xs">
	<div class='container'>
<!-- ======================================= SECTION – HERO(MAIN PICTURE) ========================================== -->
        <div id="category" class="category-carousel hidden-xs">
          <div class="item">
            <div class="image">
                <img src="{% if poster.image %}{{ poster.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" alt="" class="img-responsive" width="1140" height="400">
            </div>
          </div>
        </div>
    <div class="info">
        {% if poster %}
            <p><h3>{{ poster.poster_title1 }} </h3></p><br>
            <p><h4>Деталі: </h4></p>
            <p>{{ poster.poster_context1 }}</p>
            <br><br>
        {% else %}
            <p><h3 class="text-danger">Вибачте, але даної афіши не існує, або вона не доступна у даний час! </h3></p>
        {% endif %}
    </div>
<!-- =================================== SECTION – HERO(MAIN PICTURE) : END ======================================== -->
<!-- ================================================ UPSELL PRODUCTS ============================================== -->
<section class="section featured-product wow fadeInUp" style="margin-bottom: 0px;">
	<h3 class="section-title">Товари що діють в акції</h3>
    {% if products_poster %}
	<div class="owl-carousel home-owl-carousel upsell-product custom-carousel owl-theme outer-top-xs">
        {% for product_poster in products_poster %}
          <div class="item item-carousel">
            <div class="products">
              <div class="product">
            <!-- Картинка товару -->
                <div class="product-image">
                  <div class="image">
                      <a href="{{ product_poster.get_absolute_url }}">
                        <img src="{% if product_poster.image %}{{ product_poster.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %} " alt="" height="262" width="262">
                      </a>
                  </div><!-- /.image -->
                  <!-- tag_status -->
                      {% if product_poster.tag_status %}
                        <div class="tag {{ product_poster.tag_status }}"><span>{{ product_poster.tag_status }}</span></div>
                      {% endif %}
                  <!-- tag_status : end -->
                </div><!-- /.product-image -->

              <!-- Інформація про товар(назва, ціна і т далі) -->
                <div class="product-info text-left">
                  <h3 class="name" style="margin-bottom: 0px;" >
                      <a href="{{ product_poster.get_absolute_url }}">{{ product_poster.name }}</a></h3>

                    <!-- rating stars -->
                    {% if product_poster.avg_review == None %}
                            <span class="stars-avg stars0"></span>
                        {% else %}
                        <span class="stars-avg stars{{product_poster.avg_review|floatformat:"0"}}"></span>
                    {%endif%}
                    <!-- rating stars : end -->

                  <div class="description"></div>
                  <div class="product-price">
                      <span class="price"> {{ product_poster.price }} грн. </span>
                      <span class="price-before-discount">$ 800</span>
                  </div><!-- /.product-price -->
                </div><!-- /.product-info -->

            <!-- Анімація при наведені (доати до корзини,додоти в улюблений список,порівняти) -->
                <div class="cart clearfix animate-effect">
                  <div class="action">
                    <ul class="list-unstyled">
                        <li>
                            <form action="{% url "cart:CartAdd" product_poster.id %}" method="post" class="add">
                                {% csrf_token %}
                                    <div class="hidden" > {#style="display:none;"#}
                                      {{ cart_product_form.quantity }}
                                    </div>
                                <span class="add-cart-button btn-group">
                                  <button class="btn btn-primary icon" type="submit"> <i class="fa fa-shopping-cart"></i> </button>
                                </span>
                            </form>
                        </li>

                        {% if not request.user.is_authenticated %}
                        <li class="dropdown dropdown-small lnk wishlist" title="Увійдіть, щоб додати">
                            <a href="#" class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" style="cursor: not-allowed; /*  курсор в виде стрелки */">
                                <span class="value">
                                    <i class="icon fa fa-heart"></i>
                                </span>
                            </a>
                          <ul class="dropdown-menu text-center" style="background: black">
                            <li class="col-md-12 text-center" style="padding: 0px !important;margin: 0px!important;">
                                <p style="margin: 0px!important;"><a href="{% url 'auth:LoginUser' %}">Увійдіть</a></p>
                                <p style="color: gainsboro; margin: 0px!important;">або</p>
                                <p><a href="{% url 'auth:RegisterUser' %}">Зареєструйтесь</a></p>
                            </li>
                          </ul>
                        </li>
                        {% else %}
                        <li class="lnk wishlist">
                            <a class="add-to-cart" href="{% url "wishlist:WishListAdd" product_poster.id %}" title="Wishlist">
                              <i class="icon fa fa-heart"></i>
                            </a>
                        </li>
                        {% endif %}

                        <li class="lnk">
                          <a class="add-to-cart" href="#" title="Compare">
                              <i class="fa fa-signal"></i>
                          </a>
                        </li>
                    </ul>
                  </div><!-- /.action -->
                </div><!-- /.cart -->
              </div><!-- /.product -->
            </div><!-- /.products -->
          </div><!-- /.item -->
        {% endfor %}
    </div><!-- /.home-owl-carousel -->
    {% else %}
            <div class="owl-carousel home-owl-carousel custom-carousel owl-theme" data-item="1">
                <div class="item item-carousel">
                    <div class="products" style="text-align: center;">
                        <div class="product">
                        <h3>Вибачте, але товари в даний час не доступні!</h3><br><br>
                        </div>
                    </div>
                </div>
    {% endif %}
</section><!-- /.section -->
<div class="col-md-12" style="padding-left: 0px; padding-right: 0px;">
    <a class="col-md-12 btn btn-primary cart-btn" type="button" href="{{ poster.get_absolute_url }}">
        <span><h4>Показати всі <i class="fa fa-arrow-down" aria-hidden="true" style="padding-left: 3px;"> </i></h4></span>
    </a>
</div>
<!-- ============================================== UPSELL PRODUCTS : END ============================================== -->
<br><br><br>
<div class="clearfix"></div>
<br><br><br>
<!-- ================================================ BRANDS CAROUSEL ============================================== -->
<hr style="margin-top: 5px; border: 1px solid #eee;">
<div id="brands-carousel" class="logo-slider wow fadeInUp">
  <div class="logo-slider-inner">
    <div id="brand-slider" class="owl-carousel brand-slider custom-carousel owl-theme">
      {% if brands_popular %}
        {% for brand_popular in brands_popular %}
            <div class="item m-t-15 text-center">
                <a href="{{ brand_popular.get_absolute_url }}" class="image" >
                    <img style="background-size:150px;width: 150px;" data-echo="{% if brand_popular.image %}{{ brand_popular.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" src="{% static "images/blank.gif" %}" alt="">
                </a>
                <a href="{{ brand_popular.get_absolute_url }}">
                    {{ brand_popular.name }}
                </a>
            </div>
        {% endfor %}
      {% endif %}
    </div><!-- /.owl-carousel #logo-slider -->
  </div><!-- /.logo-slider-inner -->
</div><!-- /.logo-slider -->
<!-- ============================================= BRANDS CAROUSEL : END =========================================== -->
    </div><!-- /.container -->
</div><!-- /.body-content -->
<!-- =========================================== CONTENT : END ===================================================== -->
{% endblock %}