myshop/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

myshop/myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^auth/', include('userauth.urls', namespace='auth')),
    url(r'^wishlist/', include('wishlist.urls', namespace='wishlist')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('shop.urls', namespace='shop'))
]

# настройки для работи з медіа файлами
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomePage, name='HomePage'),
    url(r'^categories/$', views.ProductList, name='ProductList'),
    url(r'^brands/$', views.BrandList, name='BrandList'),
    url(r'^brand/(?P<brand_slug>[-\w]+)/$', views.ProductList, name='ProductListByBrand'),
    url(r'^poster/(?P<poster_slug>[-\w]+)/$', views.ProductList, name='ProductListByPoster'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^catalog/(?P<catalog_slug>[-\w]+)/$', views.CatalogList, name='ProductListByCatalog'),
    url(r'^product/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^poster/(?P<poster_id>\d+)/(?P<poster_slug>[-\w]+)/$', views.PosterDetail, name='PosterDetail'),
    url(r'^contacts/$', views.Contacts, name='Contacts'),
    url(r'^guarantee/$', views.Guarantee, name='Guarantee'),
    url(r'^about/$', views.About, name='About'),
]

myshop/shop/forms.py
# **************************************************************
# Форма для того, щоб користувач міг вибирати кількість товару *
# **************************************************************

from django import forms
from .models import Comment


class CommentAddForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['product', 'created', 'author', 'verificated']
        widgets = {
            'text_comment': forms.Textarea(attrs={'class': 'form-control txt txt-review', 'rows': '5'}),
            # 'rating': forms.CheckboxSelectMultiple()
            }

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response,HttpResponseRedirect,reverse
from .models import Catalog, Category, Product, Comment, Brand, Poster
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentAddForm
from django.db.models import Avg

# Сторінка з товарами
def HomePage(request, category_slug=None):
    category = None
    catalog = None
    # new_products=None
    catalogs = Catalog.objects.all()
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm()
    products = Product.objects.filter(available=True)
    new_products = Product.objects.filter(available=True, tag_status='new').order_by('-created')[:6]
    new_products_el = Product.objects.filter(available=True, tag_status='new', category__catalog__name='Електротовари').order_by('-created')[:6]
    new_products_auto = Product.objects.filter(available=True, tag_status='new', category__catalog__name='Автотовари').order_by('-created')[:6]
    new_products_sant = Product.objects.filter(available=True, tag_status='new', category__catalog__name='Сантехніка').order_by('-created')[:6]
    best_products = Product.objects.filter(available=True).order_by('?')[:6]
    top_sales_products = Product.objects.filter(available=True, tag_status='hot').order_by('-created')[:6]
    hot_deals_products = Product.objects.filter(available=True, tag_status='hot').order_by('?')[:3]
    special_deals_products = Product.objects.filter(available=True).order_by('?')[:9]

    posters = Poster.objects.filter(active=True).order_by('-created')[:5]
    posters_one = Poster.objects.filter(active=True).order_by('created')[:1]

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/home.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'catalog': catalog,
        'catalogs': catalogs,
        'posters': posters,
        'posters_one': posters_one,
        'cart_product_form': cart_product_form,
        'new_products': new_products,
        'new_products_el': new_products_el,
        'new_products_auto': new_products_auto,
        'new_products_sant': new_products_sant,
        'best_products': best_products,
        'top_sales_products': top_sales_products,
        'hot_deals_products': hot_deals_products,
        'special_deals_products': special_deals_products,

    })

# Сторінка відображення каталогу з категоріями
def CatalogList(request, catalog_slug=None):
    catalog = None
    catalogs = Catalog.objects.all()
    categories = Category.objects.all()
    posters = Poster.objects.filter(active=True).order_by('-created')[:5]
    if catalog_slug:
        catalog = get_object_or_404(Catalog, slug=catalog_slug)
        categories = categories.filter(catalog=catalog)
    return render(request, 'shop/product/catalog_list.html', {
        'catalog': catalog,
        'catalogs': catalogs,
        'categories': categories,
        'posters': posters,
    })


# Сторінка з товарами
def ProductList(request, category_slug=None, brand_slug=None, poster_slug=None):
    category = None
    catalog = None
    catalogs = Catalog.objects.all()
    categories = Category.objects.all()
    products_list = Product.objects.filter(available=True).annotate(avg_review=Avg('comments__rating'))
    cart_product_form = CartAddProductForm()
    posters = Poster.objects.filter(active=True).order_by('-created')[:5]

    page = request.GET.get('page', 1)
    paginator = Paginator(products_list, 9)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products_list = products_list.filter(category=category)
        paginator = Paginator(products_list, 9)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        products_list = products_list.filter(brand=brand)
        paginator = Paginator(products_list, 9)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    if poster_slug:
        poster = get_object_or_404(Poster, slug=poster_slug)
        products_list = products_list.filter(poster=poster)
        paginator = Paginator(products_list, 9)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'catalog': catalog,
        'catalogs': catalogs,
        'cart_product_form': cart_product_form,
        'posters': posters,
    })


# Сторінка товару
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    if request.method == 'POST':
        comment_form = CommentAddForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.product = product
            comment.save()
            return HttpResponseRedirect(reverse('shop:ProductDetail', args=[id, slug]))
    else:
        comment_form = CommentAddForm()

    comments_list = Comment.objects.filter(product=product, verificated=True)
    # Сума всіх оцінок і коментаріїв
    review_sum = Product.objects.filter(slug=slug).annotate(avg_review=Avg('comments__rating'))
    review_count = Comment.objects.filter(product__slug=slug, verificated=True).count()
    hot_deals_products = Product.objects.filter(available=True, tag_status='hot').order_by('?')[:3]
    best_products = Product.objects.filter(available=True).order_by('?')[:6]
    posters_one = Poster.objects.filter(active=True).order_by('created')[:1]
    brands = Brand.objects.all()[:12]

    return render(request, 'shop/product/detail.html', {
        'product': product,
        'cart_product_form': cart_product_form,
        'comment_form': comment_form,
        'comments_list': comments_list,
        'review_sum': review_sum,
        'review_count': review_count,
        'hot_deals_products': hot_deals_products,
        'best_products': best_products,
        'posters_one': posters_one,
        'brands': brands,
    })


def BrandList(request):
    brands = Brand.objects.all()
    brands_popular = Brand.objects.all().order_by('?')[:12]
    # filter(products__comments__rating=1)
    return render(request, 'shop/brand/brand_list.html', {
        'brands': brands,
        'brands_popular': brands_popular,
    })

def PosterDetail(request,poster_id, poster_slug):
    poster = get_object_or_404(Poster, slug=poster_slug, id=poster_id)
    brands_popular = Brand.objects.all().order_by('?')[:12]
    products_poster = Product.objects.filter(available=True, poster__slug=poster_slug).order_by('-created')[:6]
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/poster/poster_detail.html', {
        'poster': poster,
        'brands_popular': brands_popular,
        'products_poster': products_poster,
        'cart_product_form': cart_product_form,
    })

def Contacts(request):
    return render(request, 'shop/other/contacts.html')

def Guarantee(request):
    return render(request, 'shop/other/guarantee.html')

def About(request):
    return render(request, 'shop/other/about.html')


# ----------------------------------------------------------------------------------------------------------------------
# # Сторінка з товарами
# def ProductList(request, category_slug=None):
#     category = None
#     catalog = None
#     categories = Category.objects.all()
#     catalogs = Catalog.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         # category = get_object_or_404(Category, slug=category_slug)
#         catalog = get_object_or_404(Catalog, slug=category_slug)
#         categories = categories.filter(catalog=catalog)
#         products = products.filter(category=category)
#     return render(request, 'shop/product/list.html', {
#         'catalog': catalog,
#         'catalogs': catalogs,
#         # 'category': category,
#         'categories': categories,
#         'products': products
#     })


# # Сторінка з товарами
# def ProductList(request, category_slug=None):
#     category = None
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     if category_slug:
#         category = get_object_or_404(Category, slug=category_slug)
#         products = products.filter(category=category)
#     return render(request, 'shop/product/list.html', {
#         'category': category,
#         'categories': categories,
#         'products': products
#     })

myshop/shop/templates/shop/other/about.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Про Магазин
{% endblock %}

{% block content %}
<!-- =============================================== BRADCRUMB ===================================================== -->
<div class="breadcrumb">
  <div class="container">
    <div class="breadcrumb-inner">
      <ul class="list-inline list-unstyled">
        <li><a href="{% url 'shop:HomePage' %}">Головна</a></li>
        <li class='active'>Про Магазин</li>
      </ul>
    </div><!-- /.breadcrumb-inner -->
  </div><!-- /.container -->
</div><!-- /.breadcrumb -->
<!-- =========================================== BRADCRUMB : END =================================================== -->
<!-- ==================================================== CONTENT ================================================== -->
<div class="body-content outer-top-xs" id="top-banner-and-menu">
  <div class="container">


<div class="terms-conditions-page">
<div class="row">
    <div class="col-md-12 terms-conditions">
    <h2 class="heading-title">Інтернет магазин "MASTER"</h2>
    <div class="">
        <h3>Про НАС</h3>
Інтернет-магазин елекро-інструментів та господарських товарів «Мастер» – оптимальні рішення
Відчуйте перевагу покупок онлайн на нашому сайті. Тепер не доведеться витрачати час на ходіння по магазинах.
Ми пропонуємо можливість замовлення товару в два кліка. Також наші менеджери нададуть вам потрібну інформацію
про покупку, якщо на сайті ви не знайшли відповіді на ваші запитання. Ми намагаємося забезпечити наших клієнтів
кваліфікованою технічною консультацією, тому у нас працюють тільки професіонали.
<h3>Чому ми?</h3>
Постійне оновлення товару на сайті показує наявність техніки та ціни в реальному часі. Інтернет-магазин електроніки
«Мастер» – це економія не тільки грошей, але і вашого часу. Намагаючись продумати все до найдрібніших деталей, ми
прагнемо до ідеалу. Нам важливо, щоб кожен клієнт залишився задоволений покупкою, сервісом і мінімально витраченим
часом.
Ваш час так саме важливий, як і наш, тому наша команда постійно працює над тим, щоб процес покупки був простим, зрозумілим і швидким.
Наш інтернет-магазин електроніки в Україні співпрацює тільки з перевіреними постачальниками. Але від форс-мажорних обставин, які неможливо передбачити, не застрахований ніхто. Тому наші гарантійні зобов'язання, повага до кожного покупця, швидкість реагування, допомагає усунути проблему і знайти найбільш оптимальний вихід з неприємної ситуації.
        <h3>Зміни до угоди</h3>
        <p>Ми залишаємо за собою право на власний розсуд змінити або замінити ці Загальні положення та умови, опублікувавши оновлені умови на Сайті. Ваше подальше використання Сайту після будь-яких таких змін означає, що Ви приймаєте нові Загальні положення та умови.</p>
        <h3>Контакти</h3>
        <p>Якщо у вас виникли запитання щодо цієї Угоди, зв'яжіться з нами, або <a href="{% url 'shop:Contacts' %}" class='contact-form'>Контакти</a></p>
    </div>
    </div>
</div><!-- /.row -->
</div><!-- /.sigin-in-->


















  </div><!-- /.container -->
<br><br><br><br><br>
</div><!-- /#top-banner-and-menu -->

{% endblock %}


<!-- ============================================== BRANDS CAROUSEL ============================================== -->
{#<div class="body-content outer-top-xs" id="top-banner-and-menu">#}
{#  <div class="container">  #}
{#    <div id="brands-carousel" class="logo-slider wow fadeInUp">#}
{#      <div class="logo-slider-inner">#}
{#        <div id="brand-slider" class="owl-carousel brand-slider custom-carousel owl-theme">#}
{#          {% if brands %}#}
{#            {% for brand in brands %}#}
{#                <div class="item m-t-15 text-center">#}
{#                    <a href="#" class="image" >#}
{#                        <img style="background-size:150px;width: 150px;" data-echo="{% if brand.image %}{{ brand.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" src="{% static "images/blank.gif" %}" alt="">#}
{#                    </a>#}
{#                    <a href="#">#}
{#                        {{ brand.name }}#}
{#                    </a>#}
{#                </div>#}
{#            {% endfor %}#}
{#          {% endif %}#}
{#        </div><!-- /.owl-carousel #logo-slider -->#}
{#      </div><!-- /.logo-slider-inner -->#}
{#    </div><!-- /.logo-slider -->#}
{#  </div><!-- /.container -->#}
{#<br><br><br><br><br><br>#}
{#</div><!-- /#top-banner-and-menu -->#}
<!-- ============================================== BRANDS CAROUSEL : END ============================================== -->

myshop/shop/templates/shop/other/contacts.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Контакти
{% endblock %}

{% block content %}
<!-- =============================================== BRADCRUMB ===================================================== -->
<div class="breadcrumb">
  <div class="container">
    <div class="breadcrumb-inner">
      <ul class="list-inline list-unstyled">
        <li><a href="{% url 'shop:HomePage' %}">Головна</a></li>
        <li class='active'>Контакти</li>
      </ul>
    </div><!-- /.breadcrumb-inner -->
  </div><!-- /.container -->
</div><!-- /.breadcrumb -->
<!-- =========================================== BRADCRUMB : END =================================================== -->
<!-- ==================================================== CONTENT ================================================== -->
<div class="body-content outer-top-xs" id="top-banner-and-menu">
  <div class="container">


<div class="body-content">
	<div class="container">
        <div class="contact-page">
            <div class="row">
                <div class="col-md-12 contact-map outer-bottom-vs">
    {#                    AIzaSyAxois9EpYH0tGMGNtMSwp4Zd3VnmVSG2I#}
                    <iframe src="https://www.google.com/maps/embed/v1/place?q=%D0%92%D1%83%D0%BB%D0%B8%D1%86%D1%8F%20%D1%80%D1%96%D0%B2%D0%BD%D0%B5%D0%BD%D1%81%D1%8C%D0%BA%D0%B0%2080%20%D0%B0&key=AIzaSyAxois9EpYH0tGMGNtMSwp4Zd3VnmVSG2I" width="600" height="450"  style="border:0"></iframe>
                </div>
                <div class="col-md-9 contact-form">
                    <div class="col-md-12 contact-title">
        {#                <h4>Contact Form</h4>#}
                    </div>
                </div>
            <div class="col-md-3 contact-info">
                <div class="contact-title">
                    <h4>Інформація</h4>
                </div>
                <div class="clearfix address">
                    <span class="contact-i"><i class="fa fa-map-marker"></i></span>
                    <span class="contact-span">Україна 43020, Волинська обл., м.Луцьк, вул.Рівненьська 80а</span>
                </div>
                <div class="clearfix phone-no">
                    <span class="contact-i"><i class="fa fa-mobile"></i></span>
                    <span class="contact-span">+(0332) 75-08-18<br>+(0332) 45-67-89</span>
                </div>
                <div class="clearfix email">
                    <span class="contact-i"><i class="fa fa-envelope"></i></span>
                    <span class="contact-span"><a href="#">master@gmail.com</a></span>
                </div>
            </div>
        </div><!-- /.contact-page -->
    </div>
    </div>
</div>

  </div><!-- /.container -->
<br><br><br><br><br>
</div><!-- /#top-banner-and-menu -->

{% endblock %}


<!-- ============================================== BRANDS CAROUSEL ============================================== -->
{#<div class="body-content outer-top-xs" id="top-banner-and-menu">#}
{#  <div class="container">  #}
{#    <div id="brands-carousel" class="logo-slider wow fadeInUp">#}
{#      <div class="logo-slider-inner">#}
{#        <div id="brand-slider" class="owl-carousel brand-slider custom-carousel owl-theme">#}
{#          {% if brands %}#}
{#            {% for brand in brands %}#}
{#                <div class="item m-t-15 text-center">#}
{#                    <a href="#" class="image" >#}
{#                        <img style="background-size:150px;width: 150px;" data-echo="{% if brand.image %}{{ brand.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" src="{% static "images/blank.gif" %}" alt="">#}
{#                    </a>#}
{#                    <a href="#">#}
{#                        {{ brand.name }}#}
{#                    </a>#}
{#                </div>#}
{#            {% endfor %}#}
{#          {% endif %}#}
{#        </div><!-- /.owl-carousel #logo-slider -->#}
{#      </div><!-- /.logo-slider-inner -->#}
{#    </div><!-- /.logo-slider -->#}
{#  </div><!-- /.container -->#}
{#<br><br><br><br><br><br>#}
{#</div><!-- /#top-banner-and-menu -->#}
<!-- ============================================== BRANDS CAROUSEL : END ============================================== -->